### ISSUE TITLE
Make on/off has more contrast against each other

### ISSUE THREAD

**Issue by Riajyuu** [limbo666/KeyzPal#1]
![image](https://user-images.githubusercontent.com/16912240/79419866-2bd70800-7fa7-11ea-842a-537b55a95997.png)

See the screenshot. I think it would be better to use black/white rather than a small and hard-to-notice red slash.

**Comment by cubesky** [comment]
[keyzIcon.zip](https://github.com/limbo666/KeyzPal/files/4485627/keyzIcon.zip)

I think you can use this icon designed and draw by me. If developer want to use this icon pack, feel free to use it.  It contains Light and Dark Theme icon.  

This source code is so massive, I give up to replace it by myself.

Preview  

![Full](https://user-images.githubusercontent.com/8038511/79430250-3c18d280-7ffb-11ea-8d83-22ca4f17e0b7.png)

**Comment by limbo666** [comment]
Well noted. Preparing a new release with new icons.

**Comment by limbo666** [comment]
> Well noted. Preparing a new release with new icons.


**Adopted your suggestions Version 1.0.2.7 is out**
